### ISSUE TITLE
bug:  Icons doesn't load in local builds

### ISSUE THREAD

**Issue by tfuxu** [GradienceTeam/Gradience#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Looks like AdwCustomizer tries to load its icons from default global location, instead of `builddir/testdir/share/icons`.

Error message:
```sh
(adwcustomizer:27791): Gtk-WARNING **: 18:03:47.069: Failed to load icon /usr/local/share/icons/hicolor/scalable/apps/com.github.AdwCustomizerTeam.AdwCustomizer.svg: Error opening file /usr/local/share/icons/hicolor/scalable/apps/com.github.AdwCustomizerTeam.AdwCustomizer.svg: No such file or directory
```

### To Reproduce

1. Remember to uninstall AdwCustomizer, so there aren't any icons installed globally,
2. Compile locally

### Screenshots

![Screenshot from 2022-08-15 18-20-22](https://user-images.githubusercontent.com/73042332/184674422-7b3eb63a-8cad-4400-a815-63ad6c8f913a.png)

### OS

Fedora Linux Rawhide

### Installation method

Manual using meson - main

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdwCustomizer** [comment]
Welcome on Adwaita Manager. 🥳 We really appreciate your contribution. The core team will review your issue as soon as possible.

**Comment by eli-schwartz** [comment]
This isn't a "local" build. Rather, it's an "uninstalled" build. The software is configured and compiled for installation, and often needs a bit of help to work before that.

Meson does have support for automatically setting up an uninstalled environment. You can run `meson devenv -C builddir/` and it will set up various environment stuff for you, such as $PATH so that you can just run the program normally. To further fine-tune it, there is the `meson.add_devenv()` method which can be used in meson.build to add specialized variables.

**Comment by 0xMRTT** [comment]
Fixed
