### ISSUE TITLE
bug: previews re-added in 0.3.3 are not opening

### ISSUE THREAD

**Issue by resiehnnes** [GradienceTeam/Gradience#670]
For some reason theme previews (all 3) are not opening, but in older version which had it previews were working fine.

### OS

Fedora 37 Worksation (x11)

### Version

0.3.3

### Installation method

Flatpak from Flathub

**Comment by tfuxu** [comment]
I honestly don't know why someone enabled them back. They only work on alternative installation methods, because current [functions](https://github.com/GradienceTeam/Gradience/blob/7d86b999bf47b0a1ecec281fc3a84edcc3737fbb/gradience/frontend/main.py#L1210-L1224) used to launch those previews are using `GLib.spawn_command_line_async` instruction, and this in a containerized environment which should only contain one proper program, will not work.

**Comment by daudix-UFO** [comment]
3rd variant is to disable this feature that I enabled 😅

**Comment by tfuxu** [comment]
I forgot to update this thread, but in a nutshell, we will drop current theme previews in favor of a in-house preset preview window (more info: #676). Because this is something that will take some time to implement, theme previews button will be hidden again in the next release.
