### ISSUE TITLE
feat: be able to apply gradience themes from console

### ISSUE THREAD

**Issue by Neon-44** [GradienceTeam/Gradience#671]
### Feature description

this feature would help to be able to use gradience in scripts.
something like "flatpak run *gradience-flatpak-address* gradience apply theme.json -gtk3 -gtk4 -flatpakgtk3 -flatpakgtk4" would be immensely helpful :)

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by tfuxu** [comment]
I'm currently working on porting CLI support from our outdated [PR](https://github.com/GradienceTeam/Gradience/pull/632) to a newer codebase, so you can expect it (and maybe some other fascinating stuff) in a new update that should come out in about a week.

**Comment by Neon-44** [comment]
@tfuxu that's absolutely awesome, thank you!

is there a way i can follow a project / branch on GitHub to get notified when you're finished? :)

**Comment by tfuxu** [comment]
> is there a way i can follow a project / branch on GitHub to get notified when you're finished? :)

Yes, you can set repository watching to custom, and set it to watch for new PRs:

1.  Set it to custom:
![Screenshot from 2022-12-06 22-04-15](https://user-images.githubusercontent.com/73042332/206024026-c03f11a9-0186-4b4c-9c59-d9aa90c8fbf3.png)

2. Choose pull requests option and click apply:
![Screenshot from 2022-12-06 22-05-14](https://user-images.githubusercontent.com/73042332/206024081-08d8709a-0800-414a-9187-c2493d7f115c.png)

You'll need to wait for my PR to show up, and when it shows up, you'll get a notification on Github. Just remember to disable it afterwards, because you might get flooded by the amount of notifications from our project :)

**Comment by Neon-44** [comment]
done. thanks for your help @tfuxu, really appreciate it :) :)

**Comment by Xyphyn** [comment]
I would really like this since it means I can apply themes when I switch between light and dark theme using an extension.
