### ISSUE TITLE
feat: Support Adwaita for Steam

### ISSUE THREAD

**Issue by mossymossmoss** [GradienceTeam/Gradience#715]
### Feature description

[Adwaita for Steam](https://github.com/tkashkin/Adwaita-for-Steam) is a theme for Steam which brings it close to what standard Adwaita apps look like. It supports recoloring, and having this done when using Gradience to apply a theme would be useful

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by tfuxu** [comment]
There is already a plugin request for it here: https://github.com/GradienceTeam/Plugins/issues/1.
We might look into that soon, because [color theme support](https://github.com/tkashkin/Adwaita-for-Steam/pull/106) was recently merged to Adwaita for Steam.
For now I'm closing this issue as duplicate, check the above issue for updates.
