### ISSUE TITLE
bug: theme is not applied 

### ISSUE THREAD

**Issue by giorgos-epitropou-obs** [GradienceTeam/Gradience#743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Theme is not applied to my shell

### To Reproduce

Tried to apply any color combination with monet engine but it only works for the current Grandience window

### Screenshots

![Screenshot from 2023-03-23 11-03-58](https://user-images.githubusercontent.com/79846040/227154996-1f3679cc-31b2-4e3d-8cf5-3b55556eda07.png)

### OS

ubuntu 22.04.02 LTS

### DE/WM version

GNOME 42.5

### Version

0.4.1

### Installation method

Flatpak from Flathub

### Enabled system extensions (GNOME specific)

user-theme@gnome-shell-extensions.gcampax.github.com
hidetopbar@mathieu.bidon.ca
Vitals@CoreCoding.com
clipboard-indicator@tudmotu.com
transparent-top-bar@ftpix.com
Move_Clock@rmy.pobox.com
openweather-extension@jenslody.de
dash-to-dock@micxgx.gmail.com
ding@rastersoft.com
ubuntu-appindicators@ubuntu.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tfuxu** [comment]
Does it work with presets? Try applying a preset from Preset Manager and relog to apply changes to all apps. Also, if you didn't did that yet, enable Flatpak theming in Gradience's preferences.

**Comment by daudix-UFO** [comment]
Also, make sure to have adw-gtk3 theme installed, it's required for gtk3 theming

**Comment by giorgos-epitropou-obs** [comment]
* nope it also doesnt work for presets and yes I have enabled both theming options from preferences. I tried to read and apply all the suggestions from similar issues
* about the adw-gtk3 theme, isn't this unrelated with my basic shell apps? I mean nautilus for example shouldn work without the gtk3 stuff

**Comment by tfuxu** [comment]
Not having a `adw-gtk3` theme installed is actually related here, because you are on Ubuntu 22.04 where nautilus is still in version 42.2, still using GTK3. They ported nautilus to Libadwaita only recently in 43. This also would mean that many other GNOME apps might be still in GTK3 versions on your system. 

From what I recall, Calculator was ported early to Libadwaita, so you can test Monet Engine on it and also you could test some more Flatpak packages to check if Gradience works properly with them too.
